application: vmdevapp
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  static_files: static/HTML/index.html
  upload: static\/HTML\/index\.html
  
- url: /.*
  script: helloworld.application

libraries:
- name: webapp2
  version: latest
